/*
  Warnings:

  - You are about to drop the column `authorId` on the `Post` table. All the data in the column will be lost.
  - You are about to drop the column `content` on the `Post` table. All the data in the column will be lost.
  - You are about to drop the column `published` on the `Post` table. All the data in the column will be lost.
  - You are about to drop the `Widget` table. If the table is not empty, all the data it contains will be lost.
  - Added the required column `body` to the `Post` table without a default value. This is not possible if the table is not empty.
  - Added the required column `updated_at` to the `Post` table without a default value. This is not possible if the table is not empty.
  - Added the required column `user_id` to the `Post` table without a default value. This is not possible if the table is not empty.
  - Added the required column `password` to the `User` table without a default value. This is not possible if the table is not empty.
  - Added the required column `username` to the `User` table without a default value. This is not possible if the table is not empty.
  - Made the column `name` on table `User` required. This step will fail if there are existing NULL values in that column.

*/
-- DropForeignKey
ALTER TABLE "Post" DROP CONSTRAINT "Post_authorId_fkey";

-- DropIndex
DROP INDEX "User_email_key";

-- AlterTable
ALTER TABLE "Post" DROP COLUMN "authorId";
ALTER TABLE "Post" DROP COLUMN "content";
ALTER TABLE "Post" DROP COLUMN "published";
ALTER TABLE "Post" ADD COLUMN     "body" STRING NOT NULL;
ALTER TABLE "Post" ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Post" ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL;
ALTER TABLE "Post" ADD COLUMN     "user_id" INT4 NOT NULL;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "age" INT4;
ALTER TABLE "User" ADD COLUMN     "equipment" BOOL;
ALTER TABLE "User" ADD COLUMN     "experience" INT4;
ALTER TABLE "User" ADD COLUMN     "goals" STRING;
ALTER TABLE "User" ADD COLUMN     "height" INT4;
ALTER TABLE "User" ADD COLUMN     "online_status" BOOL;
ALTER TABLE "User" ADD COLUMN     "password" STRING NOT NULL;
ALTER TABLE "User" ADD COLUMN     "profile_pic" STRING;
ALTER TABLE "User" ADD COLUMN     "sex" STRING;
ALTER TABLE "User" ADD COLUMN     "trainer" BOOL;
ALTER TABLE "User" ADD COLUMN     "username" STRING NOT NULL;
ALTER TABLE "User" ADD COLUMN     "weight" INT4;
ALTER TABLE "User" ALTER COLUMN "name" SET NOT NULL;

-- DropTable
DROP TABLE "Widget";

-- CreateTable
CREATE TABLE "Photo" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "post_id" INT4 NOT NULL,
    "url" STRING NOT NULL,

    CONSTRAINT "Photo_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AiChat" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT4 NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AiChat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AiChatHistory" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ai_chat_id" INT4 NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "message" STRING NOT NULL,
    "is_ai" BOOL NOT NULL,

    CONSTRAINT "AiChatHistory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DirectMessage" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "sender_id" INT4 NOT NULL,
    "recipient_id" INT4 NOT NULL,
    "chat" STRING NOT NULL,

    CONSTRAINT "DirectMessage_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Post" ADD CONSTRAINT "Post_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Photo" ADD CONSTRAINT "Photo_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "Post"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AiChat" ADD CONSTRAINT "AiChat_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AiChatHistory" ADD CONSTRAINT "AiChatHistory_ai_chat_id_fkey" FOREIGN KEY ("ai_chat_id") REFERENCES "AiChat"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DirectMessage" ADD CONSTRAINT "DirectMessage_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DirectMessage" ADD CONSTRAINT "DirectMessage_recipient_id_fkey" FOREIGN KEY ("recipient_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
